import * as showTask from "./modules/showTask.js";
import * as deadline from "./modules/deadline.js";
import * as board from "./modules/board.js";
import * as dragDrop from "./modules/dragDrop.js";
import * as tabs from "./modules/tabs.js";
showTask.showTask();
deadline.deadline();
board.board();
dragDrop.dragDrop();
tabs.tabs();